import demoBlazePage from "./demoBlazePage";

describe('e-shop testing', () => {
    const demoBlazeData = require('../../../fixtures/demoBlaze.json')
    it('Create new Account', () => {
        cy.visit('https://www.demoblaze.com/')
        demoBlazePage.clickButtonByLocator('#signin2')
        demoBlazePage.sendText('#sign-username', demoBlazeData.firstName)
        cy.wait(1000)
        demoBlazePage.sendText('#sign-password', demoBlazeData.password)
        cy.wait(1000)
        demoBlazePage.clickButtonByText('.btn-primary', 'Sign up')

        // cy.get('#alertBox').click();
        // cy.on('window:alert',(txt) =>{
        //     expect(txt).to.contains('Sign up successful.')
        // })
    })
    it('Adding products', () => {
        cy.visit('https://www.demoblaze.com/')
        demoBlazePage.clickButtonByText('#login2', 'Log in')
        cy.wait(1000)
        demoBlazePage.sendText('#loginusername', demoBlazeData.firstName)
        demoBlazePage.sendText('#loginpassword', demoBlazeData.password)
        demoBlazePage.clickButtonByText('.modal-footer .btn-primary', 'Log in')
        cy.get('.list-group-item').eq(2).click()
        demoBlazePage.clickButtonByText('a', 'Sony vaio i7')
        cy.wait(1000)
        cy.contains('Add to cart').click()  
        cy.get('.nav-link').eq(0).click()
        cy.get('.list-group-item').eq(3).click()
        demoBlazePage.clickButtonByText('a', 'ASUS Full HD')
        cy.contains('Add to cart').click()
        cy.get('.nav-link').eq(3).click()
        cy.wait(1000)
        cy.get('.success').should('contain.text', demoBlazeData.laptopName)
        cy.get('.success').should('contain.text', demoBlazeData.laptopPrice)
        cy.get('.success').should('contain.text', demoBlazeData.monitorName)
        cy.get('.success').should('contain.text', demoBlazeData.monitorPrice)
        cy.get('#totalp').should('have.text', demoBlazeData.totalPrice)
        cy.contains('Place Order').click()
        demoBlazePage.sendText('#name', demoBlazeData.firstName)
        demoBlazePage.sendText('#country', demoBlazeData.Country)
        demoBlazePage.sendText('#city', demoBlazeData.City)
        demoBlazePage.sendText('#card', demoBlazeData["Credit card"])
        demoBlazePage.sendText('#month', demoBlazeData.Month)
        demoBlazePage.sendText('#year', demoBlazeData.Year)
        demoBlazePage.clickButtonByText('.btn-primary', 'Purchase')
        cy.wait(1000)
        cy.get('.showSweetAlert').contains('Thank you for your purchase!')
        cy.contains('OK').click()
})
    })